# Site wide configuration

title:			颜丙峰
description:	颜丙峰的博客
logo: 			default.jpg
teaser: 		IMG_0317.JPG
locale:	
url:

# in oder to RSS
username:		颜丙峰
# baseurl:        http://bingfengyan.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate


paginate: 12
paginate_path: "posts/:num"
# Octopress configuration

# my swiftype
swift_search:
 enable:true

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name:			颜丙峰
  email:		fxyaun@163.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: default.jpg
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
